In [2]:
import numpy as np

## Numpy basics and numpy array

In [6]:
# creating array from list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)
print()
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)
print()


# creating array from scratch
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)
print()

ones = np.ones((2, 3))
print("one array: \n", ones)
print()

full = np.full((2, 2), 7)
print("full array: \n", full)
print()

random = np.random.random((2, 3))
print("random array: \n", random)
print()

sequence = np.arange(0, 11, 2)
print("sequnce array: \n", sequence)

identity = np.eye(4)
print("\nidentity array: \n", identity)


1D array:  [1 2 3 4 5]

2D array:  [[1 2 3]
 [4 5 6]]

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]

full array: 
 [[7 7]
 [7 7]]

random array: 
 [[0.20402374 0.23364337 0.80717266]
 [0.27600568 0.91497616 0.41672709]]

sequnce array: 
 [ 0  2  4  6  8 10]

identity array: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Vector, Matrices and Tensors

In [ ]:

vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("\nMatrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("\nTensor: ", tensor)

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("\nShape :", arr.shape)
print("Dimension :", arr.ndim)
print("Size :", arr.size)
print("Data Type :", arr.dtype)
print("\nfloat values : \n", arr.astype(float)) #changing datatype of array
print()
print()



Vector:  [1 2 3]

Matrix:  [[1 2 3]
 [4 5 6]]

Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Shape  (2, 3)
Dimension  2
Size  6
Data Type  int64

float values : 
 [[1. 2. 3.]
 [4. 5. 6.]]




## Properties of Numpy array

In [5]:
# Array Reshaping
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
