### Operation on numpy arrays

In [2]:
import numpy as np
# slicing on 1D array

arr = np.array([[1,2,3],
[4,5,6],
[7,8,9]])

print(f"sliced : {arr[2:7]}")
print(f"sliced : {arr[1:8:2]}")
print(f"sliced : {arr[-3]}")

sliced : [[7 8 9]]
sliced : [[4 5 6]]
sliced : [1 2 3]


### sorting

In [3]:
unsorted = np.array([3, 1, 1, 2, 4, 2, 5, 3])
print(f"sorted: {np.sort(unsorted)}")

sorted: [1 1 2 2 3 3 4 5]


In [9]:
mat = np.array([[1,3,2],
[6,5,4],
[10,4,9]])

sorted_by_col = np.sort(mat,axis=0)
sorted_by_row = np.sort(mat,axis=1)

print(f"Original :\n {mat}")
print(f"sorted_by_col :\n {sorted_by_col}")
print(f"sorted_by_row :\n {sorted_by_row}")

Original :
 [[ 1  3  2]
 [ 6  5  4]
 [10  4  9]]
sorted_by_col :
 [[ 1  3  2]
 [ 6  4  4]
 [10  5  9]]
sorted_by_row :
 [[ 1  2  3]
 [ 4  5  6]
 [ 4  9 10]]
