### Broadcasting

- matching dimensions
- expanding single elements
- incompatible notes 

In [1]:
import numpy as np

prices = np.arange(100, 1001, 100)
print(f"prices : {prices}\n")

prices : [ 100  200  300  400  500  600  700  800  900 1000]



In [2]:
# 10% discount
disc = 10
amt = prices - (prices * disc / 100)
amt

array([ 90., 180., 270., 360., 450., 540., 630., 720., 810., 900.])

In [3]:
#  double prices
double_prices = prices * 2
print(f"double_prices : {double_prices}\n")

double_prices : [ 200  400  600  800 1000 1200 1400 1600 1800 2000]



In [ ]:
# 
matrix = np.array([[1,2,3,], [4,5,6]])  # 2 x 3
vector = np.array([7,8,9])      # 1D array with 3 elements

result = matrix + vector    # vec gets added to each rpw pf the matrix
result

array([[ 8, 10, 12],
       [11, 13, 15]])

## Vectorization

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

res = arr1 + arr2   # elememt-wise addition
res

array([5, 7, 9])

In [ ]:
mult = arr1 * arr2  # elememt-wise multiplication
mult

array([ 4, 10, 18])

In [9]:
#  logical operations
a1 = np.array([10, 20, 30])
res = a1 > 15
print(res)



[False  True  True]


In [10]:
a1= np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
res = np.dot(a1, a2) 
print(res)

[[19 22]
 [43 50]]


In [11]:
a1 = np.array([1, 2, 3])
r1 = a1.sum()
r2= a1.mean()
print(r1)   
print(r2)

6
2.0
