In [1]:
import numpy as np


### Advance Functions and Manipulation

In [2]:
arr = np.arange(10, 81,10)
print(f"original : {arr}")

new_arr = np.insert(arr, 2, 100, None)
print(f"new array : {new_arr}")
     # np.insert(arr, index, value, axis=None)

original : [10 20 30 40 50 60 70 80]
new array : [ 10  20 100  30  40  50  60  70  80]


In [3]:
arr2d = np.array([[1,2],[3,4]])
newarr = np.insert(arr2d, 1, [5,6], axis=0)
print(f"new array : \n{newarr}")

new array : 
[[1 2]
 [5 6]
 [3 4]]


In [4]:
# append
arr = np.array([10,20,30])

newarr = np.append(arr,[40,50,60])
newarr


array([10, 20, 30, 40, 50, 60])

In [5]:
# concatenate
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
newarr = np.concatenate((arr1,arr2))
newarr


array([10, 20, 30, 40, 50, 60])

In [6]:
# removing elements
arr = np.array([10,20,30,40,50,60])
newarr = np.delete(arr, 2 )     # np.delete(arr, index, axis=None)
newarr

array([10, 20, 40, 50, 60])

In [9]:
# stacking
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(f"arr1 : {arr1}")
print(f"arr2 : {arr2}\n")
print(f"vertical stack : \n{np.vstack((arr1, arr2))}")
print(f"\nhorizontal stack : \n{np.hstack((arr1, arr2))}")


arr1 : [1 2 3]
arr2 : [4 5 6]

vertical stack : 
[[1 2 3]
 [4 5 6]]

horizontal stack : 
[1 2 3 4 5 6]


In [16]:
# splitting the array
"""
np.split(arr, no. of parts, axis=0)
np.equal(arr1, arr2)
np.hsplit(arr, no. of parts)
np.vsplit(arr, no. of parts)
"""
arr = np.array([1,2,3,4,5,6,7,8])
(f"spliting array into 3 parts : {np.split(arr, 2)}")


# print(f"v stack: {np.vsplit(arr,2)}")
print(f"h split  {np.hsplit(arr, 2)}")

h split  [array([1, 2, 3, 4]), array([5, 6, 7, 8])]
