### Operation on numpy arrays

In [2]:
import numpy as np



# slicing on 1D array

arr = np.array([[1,2,3],
[4,5,6],
[7,8,9]])

print(f"sliced : {arr[2:7]}")
print(f"sliced : {arr[1:8:2]}")
print(f"sliced : {arr[-3]}")

sliced : [[7 8 9]]
sliced : [[4 5 6]]
sliced : [1 2 3]


### sorting

In [3]:
unsorted = np.array([3, 1, 1, 2, 4, 2, 5, 3])
print(f"sorted: {np.sort(unsorted)}")

sorted: [1 1 2 2 3 3 4 5]


In [4]:
mat = np.array([[1,3,2],
[6,5,4],
[10,4,9]])

sorted_by_col = np.sort(mat,axis=0)
sorted_by_row = np.sort(mat,axis=1)

print(f"Original :\n {mat}")
print(f"sorted_by_col :\n {sorted_by_col}")
print(f"sorted_by_row :\n {sorted_by_row}")

Original :
 [[ 1  3  2]
 [ 6  5  4]
 [10  4  9]]
sorted_by_col :
 [[ 1  3  2]
 [ 6  4  4]
 [10  5  9]]
sorted_by_row :
 [[ 1  2  3]
 [ 4  5  6]
 [ 4  9 10]]


### Filter 

In [5]:
num = np.arange(1,11)
even = num[num % 2 == 0]
even

array([ 2,  4,  6,  8, 10])

In [6]:
### filter by mask
nums = np.arange(1,11)

mask = nums > 4
print(f"numbers > 5 : {nums[mask]}")

numbers > 5 : [ 5  6  7  8  9 10]


### fancing indexing vs np.where()

In [7]:
# indices

indices = [0,2,4]
print("indices : ",nums[indices])

# where
cond = np.where(nums > 5)
print("cond : ",cond)
print(f"np.where() : {nums[cond]}")


indices :  [1 3 5]
cond :  (array([5, 6, 7, 8, 9]),)
np.where() : [ 6  7  8  9 10]


In [8]:
# where(cond, true values, false)
print(np.where(nums > 5, "true", "false"))
print()
print(np.where(nums > 5, nums ** 2, nums * 100))


['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']

[100 200 300 400 500  36  49  64  81 100]


### Adding and Removing data

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])


print(f"arr1 + arr2 : {arr1 + arr2}")   # adds element wise
print(f"np.concatenate((arr1, arr2)) : {np.concatenate((arr1, arr2))}")

arr1 + arr2 : [5 7 9]
np.concatenate((arr1, arr2)) : [1 2 3 4 5 6]


### array compatibility

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([2,3,5,5])
print(f"arr1.shape == arr2.shape : {arr1.shape == arr2.shape}")
print(f"arr1.shape == arr3.shape : {arr1.shape == arr3.shape}")


arr1.shape == arr2.shape : True
arr1.shape == arr3.shape : False


### adding row


In [11]:
row  = np.array([1,2,3])
new_arr = np.vstack((arr1,row))
new_arr

array([[1, 2, 3],
       [1, 2, 3]])

### adding column



In [12]:
col  = np.array([[8],[9]])
new_arr1 = np.hstack((new_arr,col))
new_arr1

array([[1, 2, 3, 8],
       [1, 2, 3, 9]])

### deleting

In [13]:
arr = np.array([1,2,3,4])
deleted = np.delete(arr,2)          # dletd elemtn at idx 2
print(f"array after deletion :{deleted}")

array after deletion :[1 2 4]


In [14]:
arr = np.array([1,2,3,4])
deleted = np.delete(arr, [0,2])          # dletd elemtn at idx 0 and 2
print(f"array after deletion :{deleted}")

array after deletion :[2 4]


### maths operation on numpy arrays

In [15]:
arr = np.array([10,20,30])
print(f"Original : {arr}")
print(f"scalar addition : {arr+5}")
print(f"scalar multiplication : {arr*5}")
print(f"scalar division : {arr/5}")
print(f"scalar exponentiation : {arr**2}")


Original : [10 20 30]
scalar addition : [15 25 35]
scalar multiplication : [ 50 100 150]
scalar division : [2. 4. 6.]
scalar exponentiation : [100 400 900]


In [16]:
# sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([-1,0,1])
print(f"sigmoid(x) : {sigmoid(x)}")

sigmoid(x) : [0.26894142 0.5        0.73105858]


In [18]:
# mean squared error
def mse(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)
y_true = np.array([1,2,3])
y_pred = np.array([1.5,2.5,3.5])
print(f"mse : {mse(y_true, y_pred)}")

mse : 0.25


In [20]:
# categorical cross entropy
def categorical_cross_entropy(y_true, y_pred):
    return -np.sum(y_true * np.log(y_pred))
y_true = np.array([0,1,0])
y_pred = np.array([0.2,0.5,0.3])
print(f"categorical_cross_entropy : {categorical_cross_entropy(y_true, y_pred)}")

categorical_cross_entropy : 0.6931471805599453


### Aggregation Function

In [17]:
arr = np.array([10,20,30,40,50,60])

print(f"Max      : {np.max(arr)}")
print(f"Min      : {np.min(arr)}")
print(f"avg      : {np.mean(arr)}")
print(f"sum      : {np.sum(arr)}")
print(f"std deviation: {np.std(arr)}")
print(f"Variance : {np.var(arr)}")

Max      : 60
Min      : 10
avg      : 35.0
sum      : 210
std deviation: 17.07825127659933
Variance : 291.6666666666667
