In [1]:
import numpy as np


### Advance Functions and Manipulation

In [5]:
arr = np.arange(10, 81,10)
print(f"original : {arr}")

new_arr = np.insert(arr, 2, 100, None)
print(f"new array : {new_arr}")
     # np.insert(arr, index, value, axis=None)

original : [10 20 30 40 50 60 70 80]
new array : [ 10  20 100  30  40  50  60  70  80]


In [8]:
arr2d = np.array([[1,2],[3,4]])
newarr = np.insert(arr2d, 1, [5,6], axis=0)
print(f"new array : \n{newarr}")

new array : 
[[1 2]
 [5 6]
 [3 4]]


In [9]:
# append
arr = np.array([10,20,30])

newarr = np.append(arr,[40,50,60])
newarr


array([10, 20, 30, 40, 50, 60])

In [11]:
# concatenate
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
newarr = np.concatenate((arr1,arr2))
newarr


array([10, 20, 30, 40, 50, 60])

In [ ]:
# removing elements
arr = np.array([10,20,30,40,50,60])
